### ISSUE TITLE
Outreachy Second Contribution 

### ISSUE THREAD

**Issue by SunSummoner** [Bioconductor/geneplotter#1]
Hi, @jwokaty @mtmorgan @dtenenba @vobencha @lwaldron 
I'm volunteering with [Sweave2Rmd](https://github.com/Bioconductor/sweave2rmd)
and we're trying to replace all Bioconductor Sweave vignettes R Markdown vignettes. 
Would you be willing to accept a pull request with the R Markdown version of geneplotter? 
We'll ask you to review and accept the pull request. You'll also need to bump the version number in your DESCRIPTION file so that the build machines will recognize that a new version is available.
Can you assign this vignette to me in the project board?
Thanks for your time.

**Comment by jwokaty** [comment]
@SunSummoner The vignettes on https://github.com/orgs/Bioconductor/projects/2/views/6 have been preselected for the Outreachy contribution period so that you don't need to contact anyone. Please select one of vignettes not assigned to anyone and make a comment in https://github.com/Bioconductor/sweave2rmd/issues/63 with the vignette you'd like to work on. I would also recommend reading the issue so that you understand what steps should be performed. I will close this issue.

**Comment by SunSummoner** [comment]
> @SunSummoner The vignettes on https://github.com/orgs/Bioconductor/projects/2/views/6 have been preselected for the Outreachy contribution period so that you don't need to contact anyone. Please select one of vignettes not assigned to anyone and make a comment in [Bioconductor/sweave2rmd#63](https://github.com/Bioconductor/sweave2rmd/issues/63) with the vignette you'd like to work on. I would also recommend reading the issue so that you understand what steps should be performed. I will close this issue.

I will do that. Thank you for you reply.

**Comment by SunSummoner** [comment]
Hi @jwokaty 
Can I work on a vignette which is not on the project list yet? Or should I wait till its there?
Thank you

**Comment by devbird007** [comment]
Hi @SunSummoner sorry to butt in like this, but the vignettes on the project list are handpicked for Outreachy applicants because they're maintained by the Bioconductor Core Team, this then makes it possible for them to review and merge your pull request when you've successfully converted a vignette to Rmd. 

You could choose to wait until the vignette you want is added to the project list, however there is no such guarantee. You also have to keep in mind that the Contribution phase has a deadline which is April 3rd and you have to have made a contribution by that date to be considered for the internship.

**Comment by SunSummoner** [comment]
Hi @devbird007 its alright, you are probably right. There are about 900 vignette so its is possible the one that I want to work with doesn't show up on the list. I just asked the permission to work with another vignette.
Thank you for your reply.

**Comment by devbird007** [comment]
You're welcome, glad I could help
